/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "por-ui",
  "description": "ui 库",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": "true // 是否首页",
        "actionText": "欢迎进入",
        "actionLink": "/introduce/",
        "features": [
          {
            "title": "por-ui简介",
            "details": "这是一个好用的简洁型 UI 库，适合移动端和 PC 端使用。目前基于Vue2，后续会更新Vue3版本。"
          },
          {
            "title": "持续集成",
            "details": "自动化测试，保证每个组件质量。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0c829d08",
      "path": "/"
    },
    {
      "title": "input 输入框",
      "frontmatter": {
        "title": "input 输入框"
      },
      "regularPath": "/components/input.html",
      "relativePath": "components/input.md",
      "key": "v-436473d6",
      "path": "/components/input.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "支持双向绑定",
          "slug": "支持双向绑定"
        }
      ]
    },
    {
      "title": "Button 按钮",
      "frontmatter": {
        "title": "Button 按钮"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-36d6936c",
      "path": "/components/button.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "带图标",
          "slug": "带图标"
        },
        {
          "level": 2,
          "title": "加载中",
          "slug": "加载中"
        },
        {
          "level": 2,
          "title": "涟漪效果",
          "slug": "涟漪效果"
        },
        {
          "level": 2,
          "title": "组合",
          "slug": "组合"
        }
      ]
    },
    {
      "title": "Layout 布局",
      "frontmatter": {
        "title": "Layout 布局"
      },
      "regularPath": "/components/layout.html",
      "relativePath": "components/layout.md",
      "key": "v-0e2a6f28",
      "path": "/components/layout.html",
      "headers": [
        {
          "level": 2,
          "title": "上中下三栏",
          "slug": "上中下三栏"
        },
        {
          "level": 2,
          "title": "添加侧边栏",
          "slug": "添加侧边栏"
        }
      ]
    },
    {
      "title": "Tabs 选项卡",
      "frontmatter": {
        "title": "Tabs 选项卡"
      },
      "regularPath": "/components/tabs.html",
      "relativePath": "components/tabs.md",
      "key": "v-10d736a8",
      "path": "/components/tabs.html",
      "headers": [
        {
          "level": 2,
          "title": "水平模式",
          "slug": "水平模式"
        },
        {
          "level": 2,
          "title": "竖直模式",
          "slug": "竖直模式"
        }
      ]
    },
    {
      "title": "Popover 浮层",
      "frontmatter": {
        "title": "Popover 浮层"
      },
      "regularPath": "/components/popover.html",
      "relativePath": "components/popover.md",
      "key": "v-26201040",
      "path": "/components/popover.html",
      "headers": [
        {
          "level": 2,
          "title": "点击方式",
          "slug": "点击方式"
        },
        {
          "level": 2,
          "title": "hover方式",
          "slug": "hover方式"
        }
      ]
    },
    {
      "title": "Toast 提示",
      "frontmatter": {
        "title": "Toast 提示"
      },
      "regularPath": "/components/toast.html",
      "relativePath": "components/toast.md",
      "key": "v-78ac5bdc",
      "path": "/components/toast.html",
      "headers": [
        {
          "level": 2,
          "title": "定时关闭",
          "slug": "定时关闭"
        },
        {
          "level": 2,
          "title": "按钮关闭",
          "slug": "按钮关闭"
        },
        {
          "level": 2,
          "title": "支持 HTML",
          "slug": "支持-html"
        }
      ]
    },
    {
      "title": "porUI",
      "frontmatter": {
        "title": "porUI"
      },
      "regularPath": "/introduce/",
      "relativePath": "introduce/README.md",
      "key": "v-48e24709",
      "path": "/introduce/",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 2,
          "title": "NPM包",
          "slug": "npm包"
        },
        {
          "level": 2,
          "title": "快速上手",
          "slug": "快速上手"
        },
        {
          "level": 2,
          "title": "现已支持",
          "slug": "现已支持"
        },
        {
          "level": 2,
          "title": "官方文档",
          "slug": "官方文档"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      }
    ],
    "sidebar": [
      {
        "title": "介绍",
        "collapsable": true,
        "children": [
          "/introduce/"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "children": [
          "/components/button"
        ]
      }
    ]
  }
}